- hosts: localhost
  gather_facts: no
  tasks:
    - name: Get device facts from vManage
      vmanage_device_facts:
        # device: 1.1.3.1
        # gather_subset:
        #     - omp
      register: device_facts

    - debug:
        var: device_facts
